# Файл конфигурации Alembic

[alembic]
# путь к скриптам миграций
script_location = alembic

# шаблон, используемый для генерации файлов миграций
# file_template = %%(rev)s_%%(slug)s

# путь sys.path, будет добавлен в начало sys.path, если присутствует.
prepend_sys_path = .

# часовой пояс для использования при рендеринге даты в файле миграции
# оставить пустым для местного времени
# timezone =

# максимальная длина символов для применения к полю "slug"
# truncate_slug_length = 40

# установить в 'true' для запуска окружения во время команды 'revision'
# revision_environment = false

# установить в 'true' для разрешения обнаружения .pyc и .pyo файлов без исходного .py файла как ревизий
# sourceless = false

# спецификация расположения версии
# version_locations = %(here)s/bar:%(version_path)s/versions

# разделитель пути версии
# version_path_separator = :

# установить в 'true' для рекурсивного поиска исходных файлов в каждом каталоге "version_locations"
# recursive_version_locations = false

# кодировка вывода, используемая при записи файлов ревизий из script.py.mako
# output_encoding = utf-8

# SQLAlchemy URL
sqlalchemy.url = postgresql://ledl_user:ledl_pass@localhost:5432/ledl_db


[post_write_hooks]
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -q

# Конфигурация логирования
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
